query AvailableAppointments {
  availableAppointments {
    edges {
      node {
        id
        timeSlot
        provider {
          id
          firstName
          lastName
        }
      }
    }
  }
}
