query AvailableAppointments {
  availableAppointments {
    edges {
      node {
        id
        timeSlot
        provider {
          id
          firstName
          lastName
        }
        reservations {
          id
          expiry
          confirmed
          expired
          client {
            id
            firstName
            lastName
          }
        }
      }
    }
  }
}
