query Clients {
  clients {
    edges {
      node {
        id
        firstName
        lastName
        reservations {
          edges {
            node {
              id
              expiry
              expired
              confirmed
              appointment {
                id
                timeSlot
              }
              provider {
                id
                firstName
                lastName
              }
            }
          }
        }
        activeReservations {
          edges {
            node {
              id
              appointment {
                id
                timeSlot
              }
              provider {
                id
                firstName
                lastName
              }
            }
          }
        }
        confirmedReservations {
          edges {
            node {
              id
              appointment {
                id
                timeSlot
              }
              provider {
                id
                firstName
                lastName
              }
            }
          }
        }
      }
    }
  }
}
