query Reservations {
  reservations {
    edges {
      node {
        id
        expiry
        expired
        confirmed
        client {
          id
          firstName
          lastName
        }
        provider {
          id
          firstName
          lastName
        }
        appointment {
          id
          timeSlot
        }
      }
    }
  }
}
